variable "ENV"              {}
variable "COMPONENT"        {}
variable "PORT"             {}
variable "INSTANCE_COUNT"   {}
variable "INSTANCE_TYPE"    {}
variable "SPOT_PRICE"       {}
variable "LB_ARN"           {}
variable "LB_DNSNAME"       {}
variable "LB_RULE_WEIGHT"   {}
variable "LISTENER_ARN"     {}
variable "HEALTH_PATH"      {}